- name: multiplay
  hosts: localhost
  vars_prompt:
   - name: user
     prompt: please enter ur name
     private: false
   - name: course
     prompt: please enter ur course name
     private: true
  tasks: 
  - name: print data
    ansible.builtin.debug:
     msg: "hi {{user}}, ur enrolled course{{password}}" #calling variable